// import { TSubscription } from 'types/subscription';
import { TFormDataState } from './types';

// const subscription = (): TSubscription => {
//   return {
//     savedValue: null,
//     subscriptions: [],
//   };
// };

const initialState: TFormDataState = {
  // sessionNo: null,
  // id: null,
  // onlineApplicationNo: null,
  // submissionDate: null,
  // onlineSalesTransactionId: null,
  // createdDateTime: null,
  // applicationForMe: subscription(),
  // startDate: subscription(),
  // ticketId: null,
  // ticketCode: null,
  // addOn: null,
  // promotionalCode: null,
  // previousCustomer: null,
  // previousCustomerReferenceNumber: subscription(),
  // currentSwiftcard: subscription(),
  // currentSwiftcardNumber: subscription(),
  // addProductToExistingCard: subscription(),
  // isApprentice: subscription(),
  // schoolName: subscription(),
  // schoolPostcode: subscription(),
  // employerName: subscription(),
  // employerPostcode: subscription(),
  // filename: subscription(),
  // payerTitle: subscription(),
  // payerFirstName: subscription(),
  // payerLastName: subscription(),
  // payerDateOfBirth: subscription(),
  // payerHomePhoneNumber: subscription(),
  // payerWorkPhoneNumber: subscription(),
  // payerMobilePhoneNumber: subscription(),
  // payerEmailAddress: subscription(),
  // currentTimeAtAddressYears: subscription(),
  // currentTimeAtAddressMonths: subscription(),
  // previousTimeAtAddressYears: subscription(),
  // previousTimeAtAddressMonths: subscription(),
  // payerCurrentPostcode: subscription(),
  // payerCurrentAddressLine1: subscription(),
  // payerCurrentAddressLine2: subscription(),
  // payerCurrentAddressLine3: subscription(),
  // payerCurrentAddressLine4: subscription(),
  // payerCurrentTown: subscription(),
  // payerPreviousPostcode: subscription(),
  // payerPreviousAddressLine1: subscription(),
  // payerPreviousAddressLine2: subscription(),
  // payerPreviousAddressLine3: subscription(),
  // payerPreviousAddressLine4: subscription(),
  // payerPreviousTown: subscription(),
  // ticketHolderTitle: subscription(),
  // ticketHolderFirstName: subscription(),
  // ticketHolderLastName: subscription(),
  // ticketHolderDateOfBirth: subscription(),
  // ticketHolderHomePhoneNumber: subscription(),
  // ticketHolderWorkPhoneNumber: subscription(),
  // ticketHolderMobilePhoneNumber: subscription(),
  // ticketHolderEmailAddress: subscription(),
  // wouldLikeNetworkClubNews: subscription(),
  // howDidYouHearAboutCentroDirectDebit: subscription(),
  // ticketHolderCurrentPostcode: subscription(),
  // ticketHolderCurrentAddressLine1: subscription(),
  // ticketHolderCurrentAddressLine2: subscription(),
  // ticketHolderCurrentAddressLine3: subscription(),
  // ticketHolderCurrentAddressLine4: subscription(),
  // ticketHolderCurrentTown: subscription(),
  // ticketHolderPreviousPostcode: subscription(),
  // ticketHolderPreviousAddressLine1: subscription(),
  // ticketHolderPreviousAddressLine2: subscription(),
  // ticketHolderPreviousAddressLine3: subscription(),
  // ticketHolderPreviousAddressLine4: subscription(),
  // ticketHolderPreviousTown: subscription(),
  // accountName: subscription(),
  // accountNumber: subscription(),
  // sortCode: subscription(),
  // relationshipToTicketHolder: subscription(),
  // has16to18Card: subscription(),
  // cardNumber16to18: subscription(),
  // imported: subscription(),
  // discarded: subscription(),
  // isChild: subscription(),
  // ticketPrice: subscription(),
  // receiveByftFree: subscription(),
  sessionNo: null,
  id: null,
  onlineApplicationNo: null,
  submissionDate: null,
  onlineSalesTransactionId: null,
  createdDateTime: null,
  applicationForMe: { savedValue: false, subscriptions: [{ section: 1, step: 4 }] },
  startDate: { savedValue: new Date(), subscriptions: [{ section: 1, step: 1 }] },
  ticketId: null,
  ticketCode: null,
  addOn: null,
  promotionalCode: null,
  previousCustomer: null,
  previousCustomerReferenceNumber: { savedValue: null, subscriptions: [] },
  currentSwiftcard: { savedValue: null, subscriptions: [] },
  currentSwiftcardNumber: { savedValue: null, subscriptions: [] },
  addProductToExistingCard: { savedValue: false, subscriptions: [{ section: 1, step: 2 }] },
  isApprentice: { savedValue: null, subscriptions: [] },
  schoolName: { savedValue: null, subscriptions: [] },
  schoolPostcode: { savedValue: null, subscriptions: [] },
  employerName: { savedValue: null, subscriptions: [] },
  employerPostcode: { savedValue: null, subscriptions: [] },
  filename: {
    savedValue: 'blob:http://localhost:3000/c2f4777a-42dd-4c7e-8488-6c38a1720321',
    subscriptions: [{ section: 2, step: 4 }],
  },
  payerTitle: { savedValue: null, subscriptions: [] },
  payerFirstName: { savedValue: 'Ticket', subscriptions: [{ section: 3, step: 1 }] },
  payerLastName: { savedValue: 'Buyer', subscriptions: [{ section: 3, step: 1 }] },
  payerDateOfBirth: { savedValue: new Date(), subscriptions: [{ section: 3, step: 2 }] },
  payerHomePhoneNumber: { savedValue: null, subscriptions: [] },
  payerWorkPhoneNumber: { savedValue: null, subscriptions: [] },
  payerMobilePhoneNumber: { savedValue: '07700900457', subscriptions: [{ section: 3, step: 3 }] },
  payerEmailAddress: {
    savedValue: 'Gilad.Grant@wmca.org.uk',
    subscriptions: [{ section: 3, step: 3 }],
  },
  currentTimeAtAddressYears: { savedValue: null, subscriptions: [] },
  currentTimeAtAddressMonths: { savedValue: null, subscriptions: [] },
  previousTimeAtAddressYears: { savedValue: null, subscriptions: [] },
  previousTimeAtAddressMonths: { savedValue: null, subscriptions: [] },
  payerCurrentPostcode: { savedValue: 'B4 6FP', subscriptions: [{ section: 3, step: 4 }] },
  payerCurrentAddressLine1: {
    savedValue: '12 Watkin Terrace',
    subscriptions: [{ section: 3, step: 4 }],
  },
  payerCurrentAddressLine2: { savedValue: '', subscriptions: [{ section: 3, step: 4 }] },
  payerCurrentAddressLine3: { savedValue: 'Northampton', subscriptions: [{ section: 3, step: 4 }] },
  payerCurrentAddressLine4: {
    savedValue: 'Northamptonshire',
    subscriptions: [{ section: 3, step: 4 }],
  },
  payerCurrentTown: { savedValue: null, subscriptions: [] },
  payerPreviousPostcode: { savedValue: null, subscriptions: [] },
  payerPreviousAddressLine1: { savedValue: null, subscriptions: [] },
  payerPreviousAddressLine2: { savedValue: null, subscriptions: [] },
  payerPreviousAddressLine3: { savedValue: null, subscriptions: [] },
  payerPreviousAddressLine4: { savedValue: null, subscriptions: [] },
  payerPreviousTown: { savedValue: null, subscriptions: [] },
  ticketHolderTitle: { savedValue: null, subscriptions: [] },
  ticketHolderFirstName: { savedValue: 'Ticket', subscriptions: [{ section: 2, step: 1 }] },
  ticketHolderLastName: { savedValue: 'User', subscriptions: [{ section: 2, step: 1 }] },
  ticketHolderDateOfBirth: {
    savedValue: new Date(),
    subscriptions: [{ section: 2, step: 2 }],
  },
  ticketHolderHomePhoneNumber: { savedValue: null, subscriptions: [] },
  ticketHolderWorkPhoneNumber: { savedValue: null, subscriptions: [] },
  ticketHolderMobilePhoneNumber: {
    savedValue: '07700900457',
    subscriptions: [{ section: 2, step: 3 }],
  },
  ticketHolderEmailAddress: {
    savedValue: 'Gilad.Grant@wmca.org.uk',
    subscriptions: [{ section: 2, step: 3 }],
  },
  wouldLikeNetworkClubNews: { savedValue: null, subscriptions: [] },
  howDidYouHearAboutCentroDirectDebit: {
    savedValue: 'ticket-finder',
    subscriptions: [{ section: 4, step: 2 }],
  },
  ticketHolderCurrentPostcode: { savedValue: 'B4 6FP', subscriptions: [{ section: 2, step: 3 }] },
  ticketHolderCurrentAddressLine1: {
    savedValue: '10 Watkin Terrace',
    subscriptions: [{ section: 2, step: 3 }],
  },
  ticketHolderCurrentAddressLine2: { savedValue: '', subscriptions: [{ section: 2, step: 3 }] },
  ticketHolderCurrentAddressLine3: {
    savedValue: 'Northampton',
    subscriptions: [{ section: 2, step: 3 }],
  },
  ticketHolderCurrentAddressLine4: {
    savedValue: 'Northamptonshire',
    subscriptions: [{ section: 2, step: 3 }],
  },
  ticketHolderCurrentTown: { savedValue: null, subscriptions: [] },
  ticketHolderPreviousPostcode: { savedValue: null, subscriptions: [] },
  ticketHolderPreviousAddressLine1: { savedValue: null, subscriptions: [] },
  ticketHolderPreviousAddressLine2: { savedValue: null, subscriptions: [] },
  ticketHolderPreviousAddressLine3: { savedValue: null, subscriptions: [] },
  ticketHolderPreviousAddressLine4: { savedValue: null, subscriptions: [] },
  ticketHolderPreviousTown: { savedValue: null, subscriptions: [] },
  accountName: { savedValue: 'Direct Debit', subscriptions: [{ section: 4, step: 1 }] },
  accountNumber: { savedValue: '12345678', subscriptions: [{ section: 4, step: 1 }] },
  sortCode: { savedValue: '123456', subscriptions: [{ section: 4, step: 1 }] },
  relationshipToTicketHolder: { savedValue: null, subscriptions: [] },
  has16to18Card: { savedValue: null, subscriptions: [] },
  cardNumber16to18: { savedValue: null, subscriptions: [] },
  imported: { savedValue: null, subscriptions: [] },
  discarded: { savedValue: null, subscriptions: [] },
  isChild: { savedValue: null, subscriptions: [] },
  ticketPrice: { savedValue: null, subscriptions: [] },
  receiveByftFree: { savedValue: null, subscriptions: [] },
};

export default initialState;
