import { TSubscription } from 'types/subscription';
import { TFormDataState } from './types';

const subscription = (): TSubscription => {
  return {
    value: null,
    subscriptions: [],
  };
};

const initialState: TFormDataState = {
  sessionNo: null,
  id: null,
  onlineApplicationNo: null,
  submissionDate: null,
  onlineSalesTransactionId: null,
  createdDateTime: null,
  applicationForMe: subscription(),
  startDate: subscription(),
  ticketId: null,
  ticketCode: null,
  addOn: null,
  promotionalCode: null,
  previousCustomer: null,
  previousCustomerReferenceNumber: subscription(),
  currentSwiftcard: subscription(),
  currentSwiftcardNumber: subscription(),
  addProductToExistingCard: subscription(),
  isApprentice: subscription(),
  schoolName: subscription(),
  schoolPostcode: subscription(),
  employerName: subscription(),
  employerPostcode: subscription(),
  filename: subscription(),
  payerTitle: subscription(),
  payerFirstName: subscription(),
  payerLastName: subscription(),
  payerDateOfBirth: subscription(),
  payerHomePhoneNumber: subscription(),
  payerWorkPhoneNumber: subscription(),
  payerMobilePhoneNumber: subscription(),
  payerEmailAddress: subscription(),
  currentTimeAtAddressYears: subscription(),
  currentTimeAtAddressMonths: subscription(),
  previousTimeAtAddressYears: subscription(),
  previousTimeAtAddressMonths: subscription(),
  payerCurrentPostcode: subscription(),
  payerCurrentAddressLine1: subscription(),
  payerCurrentAddressLine2: subscription(),
  payerCurrentAddressLine3: subscription(),
  payerCurrentAddressLine4: subscription(),
  payerCurrentTown: subscription(),
  payerPreviousPostcode: subscription(),
  payerPreviousAddressLine1: subscription(),
  payerPreviousAddressLine2: subscription(),
  payerPreviousAddressLine3: subscription(),
  payerPreviousAddressLine4: subscription(),
  payerPreviousTown: subscription(),
  ticketHolderTitle: subscription(),
  ticketHolderFirstName: subscription(),
  ticketHolderLastName: subscription(),
  ticketHolderDateOfBirth: subscription(),
  ticketHolderHomePhoneNumber: subscription(),
  ticketHolderWorkPhoneNumber: subscription(),
  ticketHolderMobilePhoneNumber: subscription(),
  ticketHolderEmailAddress: subscription(),
  wouldLikeNetworkClubNews: subscription(),
  howDidYouHearAboutCentroDirectDebit: subscription(),
  ticketHolderCurrentPostcode: subscription(),
  ticketHolderCurrentAddressLine1: subscription(),
  ticketHolderCurrentAddressLine2: subscription(),
  ticketHolderCurrentAddressLine3: subscription(),
  ticketHolderCurrentAddressLine4: subscription(),
  ticketHolderCurrentTown: subscription(),
  ticketHolderPreviousPostcode: subscription(),
  ticketHolderPreviousAddressLine1: subscription(),
  ticketHolderPreviousAddressLine2: subscription(),
  ticketHolderPreviousAddressLine3: subscription(),
  ticketHolderPreviousAddressLine4: subscription(),
  ticketHolderPreviousTown: subscription(),
  accountName: subscription(),
  accountNumber: subscription(),
  sortCode: subscription(),
  relationshipToTicketHolder: subscription(),
  has16to18Card: subscription(),
  cardNumber16to18: subscription(),
  imported: subscription(),
  discarded: subscription(),
  isChild: subscription(),
  ticketPrice: subscription(),
  receiveByftFree: subscription(),
};

export default initialState;
