import { TApiTicket } from 'types/ticket';

type TDummyData = {
  [key: string]: TApiTicket & {
    [key: string]: any;
  };
};

const dummyData: TDummyData = {
  adult: {
    id: 30,
    name: 'Monthly DirectDebit nnetwork Zone 1',
    description:
      '<p><p> Buying by Direct Debit offers you:</p> <ul> <li><strong><em>Massive savings</em></strong> - discounted travel compared to weekly and 4 weekly tickets.</li> <li><strong><em>Convenience</em></strong>- no more queuing for tickets we deliver straight to your door</li> <li><strong><em>Ease</em></strong> - just continue to use your Swift card each time you travel whilst you\'re a member of the Direct Debit scheme, no need to have a new ticket each month.</li> <li><strong><em>Security</em></strong> - Swift is easily replaced with one simple phone call</li> <li><strong><em>Hassle free </em></strong> -use the apply button above to complete the quick and easy online application. </ul>\n<p>Start saving now – apply online today</p><p><strong>Swift</strong></p><p><strong>New to swift?</strong></p><p>Direct Debit tickets are only available online and will come loaded onto a swift photocard. This photocard can be reused for future ticket purchases or renewals.</p>\n<p><strong>Existing swift photocard holder?</strong></p><p>If you already hold a photocard, you can choose to use our Click and Collect service. Just enter your photocard number during your Direct Debit application and collect your ticket onto your card using the Swift Collector app, or at over 100 on-street Swift Collectors. Alternatively, you can be sent a new photocard when your ticket is ready.</p></p><p><p><strong>Save on days out</strong></p><p>Entitles ticket holder to discounts at local attractions. Just show your ticket or Swift card together with one of our vouchers. Download <a href="https://www.networkwestmidlands.com/offers/discount-vouchers/ ">here</a>.</p></p><p><p>*Valid on bus services, run by operators in the Centrocard Ticket Scheme within the <a href="https://cloudcdn.wmca.org.uk/documents/nwm/nbus_nnetworkMap.pdf">West Midlands area</a>.   You can find out which operator accepts them <a href="https://journeyplanner.networkwestmidlands.com/operator">here</a> </p></p>',
    summary: 'Regional bus* plus train travel within the specified Rail Zones',
    type: 'Ticket',
    brandId: '3dab38e2-9cb6-e411-842f-0050568f6585',
    brand: 'nnetwork',
    firstClass: false,
    allowBus: true,
    allowMetro: false,
    allowTrain: true,
    allowPeakTravel: true,
    timeLimited: false,
    networkTicket: true,
    operatorId: '74ab7f8a-7c80-e411-9265-0050568f6584',
    operator: 'All Operators*',
    outOfCounty: false,
    passengerTypeId: 450930000,
    passengerType: 'Adult',
    requirePhotocard: true,
    railZoneFrom: 1,
    railZoneTo: 1,
    validityId: 450930002,
    validity: '1 Month',
    busTravelAreaId: 450930003,
    busTravelArea: 'West Midlands',
    directDebitCode: 'JMA',
    startDate: '2010-01-02T00:00:00+00:00',
    endDate: '2051-01-01T23:59:59.999+00:00',
    ticketCurrentAmount: 77.5,
    standardCurrentAmount: 77.5,
    priceOverride: '',
    purchaseLocations: {
      natEx: false,
      railStation: false,
      tic: false,
      payzone: false,
      onBus: false,
      onMetro: false,
      onSSP: false,
      swiftKiosk: false,
      swiftOnMobile: false,
      swiftRemoteRetail: false,
    },
    buyOnDirectDebit: true,
    buyOnDirectPurchase: false,
    buyOnSwift: true,
    documents: [
      {
        id: '8392946b-2f59-e411-a159-0050568f6585',
        name: 'Terms and Conditions nNetwork',
      },
    ],
    features: [
      {
        id: 'bed592b9-add3-e811-9e16-0050568f6584',
        name: 'Swift photocard',
        referenceCode: '019',
        description: 'Swift is the travel smartcard of the region, find out more below.',
      },
      {
        id: '83e59573-add3-e811-9e16-0050568f6584',
        name: 'Adult',
        referenceCode: '001',
        description: '',
      },
      {
        id: 'd71a4ed4-1be8-e811-9e16-0050568f6584',
        name: 'Anytime Travel',
        referenceCode: '010',
        description: 'This ticket does not have any time restrictions applied.',
      },
      {
        id: '2d58f1e2-aad3-e811-9e16-0050568f6584',
        name: 'Friends and Family Discount',
        referenceCode: '028',
        description:
          '<p>Travel off-peak between two stations for £1 for one adult and 50p each for up to two children, accompanied by a valid adult season ticket holder. </p><p>Network West Midlands area only. Purchase from your local rail station.</p>',
      },
      {
        id: 'a5feb46b-ccec-e811-9e16-0050568f6584',
        name: 'Any bus*',
        referenceCode: '007',
        description:
          '<p>*Valid on the bus services in the specified area run by operators in the <a href="https://journeyplanner.networkwestmidlands.com/operator">nBus Ticket Scheme (nBus) or Centrocard Ticket Scheme (nnetwork)</a>.',
      },
    ],
    orderSequence: 2,
    timePeriod1: true,
    timePeriod2: true,
    timePeriod3: true,
    timePeriod4: true,
    displayInSwiftSearch: true,
    isSingleOperatorTicket: true,
    isPayAsYouGo: false,
    hasAddOn: false,
    hasPurchaseChannel: true,
    hasOnlinePurchaseChannel: true,
    isAdult: false,
    isChild: true,
    isStudent: false,
    isConcessionary: false,
    isFamily: false,
    buyTicketUrl: 'https://ticketing.cenapps.org.uk/DirectDebit/30',
    relatedTickets: [],
  },
  student: {
    id: 660027,
    name: 'Student Coventry nbus Direct Debit',
    description:
      '<p>Whatever you\'re travelling for, your journey to college or uni, shopping trips, evenings out or visiting friends, there\'s no need to worry - this ticket is all you need.\n<p> Buying by Direct Debit offers you:</p> <ul> <li><strong><em>Massive savings</em></strong> - discounted travel compared to termly tickets.</li> <li><strong><em>Convenience</em></strong>- no more queuing for tickets we deliver straight to your door</li> <li><strong><em>Ease</em></strong> - just continue to use your Swift card each time you travel whilst you\'re a member of the Direct Debit scheme, no need to have a new ticket each month.</li> <li><strong><em>Security</em></strong> - Swift is easily replaced with one simple phone call</li> <li><strong><em>Hassle free </em></strong> -use the apply button above to complete the quick and easy online application. </ul>\n<p>Start saving now – apply online today</p><p><strong>Swift</strong></p><p><strong>New to swift?</strong></p><p>Direct Debit tickets are only available online and will come loaded onto a swift photocard. This photocard can be reused for future ticket purchases or renewals.</p>\n<p><strong>Existing swift photocard holder?</strong></p><p>If you already hold a photocard, you can choose to use our Click and Collect service. Just enter your photocard number during your Direct Debit application and collect your ticket onto your card using the Swift android app, or at over 100 on-street Swift Collectors. Alternatively, you can be sent a new photocard when your ticket is ready.</p></p><p>Available to students who are in full time education aged 18+ or those aged 16-18 who are NOT entitled to the Network West Midlands <strong><a href="https://journeyplanner.networkwestmidlands.com/operator">16-18 photocard</a></strong>. Proof of full time education will be required to buy this ticket.</p><p>*Valid on bus services in the <a href="https://cloudcdn.wmca.org.uk/documents/nwm/nbus_nnetworkMap.pdf">specified area</a> run by operators in the nbus Ticket Scheme.  You can find out which operator accepts them <a href="https://journeyplanner.networkwestmidlands.com/operator">here</a> </p></p><p><p><strong>Save on days out</strong></p><p>Entitles ticket holder to discounts at local attractions. Just show your ticket or Swift card together with one of our vouchers. Download <a href="https://www.networkwestmidlands.com/offers/discount-vouchers/ ">here</a>.</p></p>',
    summary:
      'Unlimited travel on all buses<small><strong>*</strong></small>, all day in the <a href="http://static.centro.org.uk/documents/nwm/nbus_nnetworkMap.pdf"> Coventry Area </a>',
    type: 'Ticket',
    brandId: '43ab38e2-9cb6-e411-842f-0050568f6585',
    brand: 'nbus',
    firstClass: false,
    allowBus: true,
    allowMetro: false,
    allowTrain: false,
    allowPeakTravel: true,
    timeLimited: false,
    networkTicket: false,
    operatorId: '74ab7f8a-7c80-e411-9265-0050568f6584',
    operator: 'All Operators*',
    outOfCounty: false,
    passengerTypeId: 450930004,
    passengerType: 'Student18Plus',
    requirePhotocard: true,
    validityId: 450930002,
    validity: '1 Month',
    busTravelAreaId: 450930002,
    busTravelArea: 'Coventry',
    directDebitCode: 'DDSTUNBUSCOV',
    startDate: '2019-08-16T00:00:00+01:00',
    endDate: '2050-01-01T23:59:59.999+00:00',
    ticketCurrentAmount: 33.5,
    standardCurrentAmount: 35.0,
    standardDiscountCurrentAmount: 33.5,
    priceOverride: '',
    purchaseLocations: {
      natEx: false,
      railStation: false,
      tic: false,
      payzone: false,
      onBus: false,
      onMetro: false,
      onSSP: false,
      swiftKiosk: false,
      swiftOnMobile: false,
      swiftRemoteRetail: false,
    },
    buyOnDirectDebit: true,
    buyOnDirectPurchase: false,
    buyOnSwift: true,
    documents: [
      {
        id: '6768660b-2045-e611-9d6e-0050568f6584',
        name: 'Terms & Conditions Student nBus',
      },
    ],
    features: [
      {
        id: 'a5feb46b-ccec-e811-9e16-0050568f6584',
        name: 'Any bus*',
        referenceCode: '007',
        description:
          '<p>*Valid on the bus services in the specified area run by operators in the <a href="https://journeyplanner.networkwestmidlands.com/operator">nBus Ticket Scheme (nBus) or Centrocard Ticket Scheme (nnetwork)</a>.',
      },
      {
        id: 'd71a4ed4-1be8-e811-9e16-0050568f6584',
        name: 'Anytime Travel',
        referenceCode: '010',
        description: 'This ticket does not have any time restrictions applied.',
      },
      {
        id: 'dea8e055-add3-e811-9e16-0050568f6584',
        name: 'Student',
        referenceCode: '004',
        description:
          '<p>Available to students who are in full time education aged 18+ or those aged 16-18 who are NOT entitled to the Network West Midlands <a href="https://journeyplanner.networkwestmidlands.com/operator">16-18 photocard</a>. Proof of full time education and two passport sized photographs will be required to buy this ticket (if purchasing from rail station). Or, it may be loaded to a Swift photocard.</p>',
      },
      {
        id: 'bed592b9-add3-e811-9e16-0050568f6584',
        name: 'Swift photocard',
        referenceCode: '019',
        description: 'Swift is the travel smartcard of the region, find out more below.',
      },
    ],
    orderSequence: 3,
    timePeriod1: true,
    timePeriod2: true,
    timePeriod3: true,
    timePeriod4: true,
    displayInSwiftSearch: true,
    isSingleOperatorTicket: true,
    isPayAsYouGo: false,
    hasAddOn: false,
    hasPurchaseChannel: true,
    hasOnlinePurchaseChannel: true,
    isAdult: false,
    isChild: true,
    isStudent: true,
    isConcessionary: false,
    isFamily: false,
    buyTicketUrl: 'https://ticketing.cenapps.org.uk/DirectDebit/660027',
    relatedTickets: [],
  },
};

export default dummyData;
